<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
  public function run(): void
  {
    // Flattened list of products associated with their EXACT Sub-Category name.
    // We will look up the sub-category ID based on this name.
    $productsBySubcategory = [
      'Bricks and Blocks' => [
        ['name' => 'M6 BLOCK A+ SABS 390x140x190', 'image' => 'images/products/A_PLUS_BLOCK.png'],
        ['name' => 'M6 BLOCK B+ 390X140X170', 'image' => 'images/products/B_PLUS_BLOCK.png'],
        ['name' => 'M6 BLOCK C+ 345X120X160', 'image' => 'images/products/C_PLUS_BLOCK.png'],
        ['name' => 'M8 BLOCK 390X190X190', 'image' => 'images/products/M8_BLOCK.png'],
        ['name' => 'M4 BLOCK SABS', 'image' => 'images/products/M4_SABS.png'],
        ['name' => 'M4 BLOCK non-SABS', 'image' => 'images/products/M4_BLOCK.png'],
        ['name' => 'Stock Brick', 'image' => 'images/products/jabulani_stock_brick.png'],
        ['name' => 'Paving Brick Terracota', 'image' => 'images/products/PAVING_TERRA.png'],
        ['name' => 'Paving Brick Grey', 'image' => 'images/products/PAVING_GREY.png'],
      ],
      'Aluminium Windows and Doors' => [
        ['name' => 'PTT 1212 BRONZE', 'image' => 'images/products/PTT1212.png'],
        ['name' => 'PTT 189 WINDOW', 'image' => 'images/products/PTT189.png'],
        ['name' => 'PTT 1515 WINDOW', 'image' => 'images/products/PTT1515.png'],
        ['name' => 'PT 69 WINDOW', 'image' => 'images/products/PT69.png'],
        ['name' => 'PT 129 WINDOW', 'image' => 'images/products/PT129.png'],
        ['name' => 'P4 1815 WINDOW', 'image' => 'images/products/P41815.png'],
        ['name' => 'Single Sidlight PT621', 'image' => 'images/products/sidelight621.png'],
        ['name' => 'PT 189 WINDOW', 'image' => 'images/products/PT189.png'],
        ['name' => 'Simple Aluminium Door 5-Panel/3', 'image' => 'images/products/Aluminium_5panel.png'],
        ['name' => 'Single Sidelight Door', 'image' => 'images/products/Single_sidelight_door.png'],
        ['name' => 'Double Sidelight Door', 'image' => 'images/products/Double_sidelight_door.png'],
        ['name' => 'Stabel/Half Door', 'image' => 'images/products/stable_door.png'],
        ['name' => 'Fancy Stable/Half Door', 'image' => 'images/products/Fancy_stable_door.png'],
        ['name' => 'Pivot Door', 'image' => 'images/products/Pivot_Door.png'],
        ['name' => 'Double Door', 'image' => 'images/products/double_door.png'],
      ],
      'Structural and Concrete' => [
        ['name' => 'Lintels from 1M to 6M', 'image' => 'images/products/Lintels.png'],
        ['name' => 'Column Pillar from Small to Big', 'image' => 'images/products/PILLAR.png'],
        ['name' => 'Header Fitter from Small to Big', 'image' => 'images/products/headerFitter.png'],
        ['name' => 'Concrete Window Sill', 'image' => 'images/products/windowSill.png'],
        ['name' => 'Toilet Slab', 'image' => 'images/products/Toilet_Slab.png'],
        ['name' => 'Grave Slab', 'image' => 'images/products/Grave Slab.png'],
      ],
      'Roofing' => [
        ['name' => 'Jabulani Roof Tile Terracota', 'image' => 'images/products/roof_burgandy.png'],
        ['name' => 'Jabulani Roof Tile Black', 'image' => 'images/products/roof_black.png'],
        ['name' => 'Jabulani Roof Tile Green', 'image' => 'images/products/roof_green.png'],
        ['name' => 'Jabulani Roof Tile Charcoal', 'image' => 'images/products/roof_charcoal.png'],
        ['name' => 'Jabulani Roof Tile Burgandy', 'image' => 'images/products/ROOF_TERR.png'],
        ['name' => 'Angle Ridging', 'image' => 'images/products/angle_ridging.png'],
        ['name' => 'Jabulani Roof Tile Elite/Heavy Duty in All Colors', 'image' => 'images/products/roof_elite.png'],
      ],
      'Jabulani Tile Adhesive' => [
        ['name' => 'Jabulani Tylon Porcelain', 'image' => 'images/products/jb_adhesive1.webp'],
        ['name' => 'Jabulani Tylon Ceramic', 'image' => 'images/products/jb_adhesive2.webp'],
      ],
      'Crush Stone' => [
        ['name' => 'Crush Dust', 'image' => 'images/products/crushDust.webp'],
        ['name' => '13mm Crush Stone', 'image' => 'images/products/crush13mm.jpg'],
        ['name' => '19mm Crush Stone', 'image' => 'images/products/crush19mm.jpg'],
        ['name' => 'Gabion Stone', 'image' => 'images/products/gabionStone.jpg'],
      ],
      'Brick and Blocks' => [
        ['name' => 'Stock/Common Brick', 'image' => 'images/products/jabulani_stock_brick.png'],
        ['name' => 'Face Brick Blue Barley', 'image' => 'images/products/blue_barley.png'],
        ['name' => 'Face Brick Saphhire Satin', 'image' => 'images/products/satin.png'],
        ['name' => 'Face Brick Golden Wheat', 'image' => 'images/products/golden.png'],
        ['name' => 'Paving Brick Terracota', 'image' => 'images/products/PAVING_TERRA.png'],
        ['name' => 'Paving Brick Grey', 'image' => 'images/products/PAVING_GREY.png'],
        ['name' => 'M6 BLOCK A+ SABS 390x140x190', 'image' => 'images/products/A_PLUS_BLOCK.png'],
        ['name' => 'M6 BLOCK B+ 390X140X170', 'image' => 'images/products/B_PLUS_BLOCK.png'],
        ['name' => 'M6 BLOCK C+ 345X120X160', 'image' => 'images/products/C_PLUS_BLOCK.png'],
        ['name' => 'M8 BLOCK 390X190X190', 'image' => 'images/products/M8_BLOCK.png'],
        ['name' => 'M4 BLOCK SABS', 'image' => 'images/products/M4_SABS.png'],
        ['name' => 'M4 BLOCK non-SABS', 'image' => 'images/products/M4_BLOCK.png'],
      ],
      'Concrete and Structural' => [
        ['name' => 'Lintels from 1M to 6M', 'image' => 'images/products/Lintels.png'],
        ['name' => 'Column Pillar Concrete Small to Big', 'image' => 'images/products/PILLAR.png'],
        ['name' => 'Header Footer from Small to Big', 'image' => 'images/products/headerFitter.png'],
        ['name' => 'Concrete Window Sill', 'image' => 'images/products/windowSill.png'],
        ['name' => 'Toilet Slab', 'image' => 'images/products/Toilet_Slab.png'],
        ['name' => 'Grave Slab', 'image' => 'images/products/Grave Slab.png'],
        ['name' => 'Nutec Window Sill', 'image' => 'images/products/nutec_window_sill.png'],
        ['name' => 'Nutec Pillar Concrete Small to Big', 'image' => 'images/products/Nutec_pillar.png'],
      ],
      'Cement and Premixes' => [
        ['name' => 'NPC Black 42.5 N 50kg', 'image' => 'images/products/npc_black.png'],
        ['name' => 'NPC Blue 32.5 N 50kg', 'image' => 'images/products/npc_blue.png'],
        ['name' => 'Alpine 42.5 N 50kg', 'image' => 'images/products/alpine.png'],
        ['name' => 'Afrisam 42.5 N 50kg', 'image' => 'images/products/afrisam_blue.png'],
        ['name' => 'Afrisam 52.5 N 50kg', 'image' => 'images/products/afrisam_black.png'],
        ['name' => 'Powafix Crackfiller 500g to 20kg', 'image' => 'images/products/crack_filler.png'],
        ['name' => 'Powafix Cement Oxide', 'image' => 'images/products/cement_oxide.png'],
        ['name' => 'Woodfiller', 'image' => 'images/products/woodfiller.png'],
        ['name' => 'Glue Devil Contractors', 'image' => 'images/products/contractors.png'],
      ],
      'Structural Steel' => [
        ['name' => 'Square Tube All Sizes', 'image' => 'images/products/square_tube.png'],
        ['name' => 'Rectangular Tube All Sizes', 'image' => 'images/products/rectangular_tube.png'],
        ['name' => 'Round Tube All Sizes', 'image' => 'images/products/round_tube.png'],
        ['name' => 'Flat Bar All Sizes', 'image' => 'images/products/flat_bar.png'],
        ['name' => 'Galvanized Flat Sheet', 'image' => 'images/products/flat_sheet.png'],
        ['name' => 'Angle All Sizes', 'image' => 'images/products/angle_steel.png'],
      ],
      'Reinforcing and Underlay' => [
        ['name' => 'Y Bar All Sizes', 'image' => 'images/products/y_bar.png'],
        ['name' => 'Round Bar All Sizes', 'image' => 'images/products/round_bar.png'],
        ['name' => 'Weld Mesh All Sizes', 'image' => 'images/products/weld_mesh.png'],
        ['name' => 'DPC Sheet SABS', 'image' => 'images/products/DPC.png'],
        ['name' => 'Brick Force Galvanized', 'image' => 'images/products/brick_force.png'],
        ['name' => 'Hoop Iron', 'image' => 'images/products/hoop.png'],
        ['name' => 'Square Bar All Sizes', 'image' => 'images/products/sqaure_bar.png'],
      ],
      'Roof Tiles' => [
        ['name' => 'Roman Tile Ceramic Red', 'image' => 'images/products/roman_red.png'],
        ['name' => 'Roman Tile Ceramic Grey', 'image' => 'images/products/roman_grey.png'],
        ['name' => 'Jabulani Roof Tile Terracota', 'image' => 'images/products/roof_burgandy.png'],
        ['name' => 'Jabulani Roof Tile Black', 'image' => 'images/products/roof_black.png'],
        ['name' => 'Jabulani Roof Tile Green', 'image' => 'images/products/roof_green.png'],
        ['name' => 'Jabulani Roof Tile Charcoal', 'image' => 'images/products/roof_charcoal.png'],
        ['name' => 'Jabulani Roof Tile Burgandy', 'image' => 'images/products/ROOF_TERR.png'],
        ['name' => 'Jabulani Roof Tile Elite/Heavy Duty in All Colors', 'image' => 'images/products/roof_elite.png'],
        ['name' => 'Angle Ridging', 'image' => 'images/products/angle_ridging.png'],
      ],
      'Roof Sheeting' => [
        ['name' => 'Corrugated Roof Sheets Galv', 'image' => 'images/products/corrugated.png'],
        ['name' => 'IBR Roof Sheet All Sizes', 'image' => 'images/products/ibr.png'],
        ['name' => 'Ridging IBR Galv All Size', 'image' => 'images/products/ridge.png'],
        ['name' => 'Corrugated Iron Sheets', 'image' => 'images/products/iron.png'],
        ['name' => 'Polycarbonated Roof Sheets', 'image' => 'images/products/polycarb.png'],
        ['name' => 'Ridging Rolltop Galv', 'image' => 'images/products/ridging.png'],
        ['name' => 'Aluminium Flashing', 'image' => 'images/products/flashing.png'],
        ['name' => 'IBR Closure Ridge', 'image' => 'images/products/closure.png'],
      ],
      'Fascia and Barge' => [
        ['name' => 'Nutec Fascia Boards', 'image' => 'images/products/nutec_fascia.png'],
        ['name' => 'Fascia Board joiner', 'image' => 'images/products/joiner.png'],
        ['name' => 'PVC Fascia Board', 'image' => 'images/products/fascia_pvc.png'],
        ['name' => 'Pine Fascia Board', 'image' => 'images/products/fascia_pine.png'],
        ['name' => 'Steel Fascia Boards', 'image' => 'images/products/fascia_steel.png'],
        ['name' => 'Nutec Barge Board', 'image' => 'images/products/barge_nutec.png'],
        ['name' => 'PVC Barge Board', 'image' => 'images/products/barge_pvc.png'],
        ['name' => 'Galvanized Barge Board', 'image' => 'images/products/barge_galvanized.png'],
        ['name' => 'U PVC Barge Connector', 'image' => 'images/products/barge_connector.png'],
        ['name' => 'Barge Joiner Nutec', 'image' => 'images/products/barge_joiner.png'],
      ],
      'Ceiling Boards and Pine' => [
        ['name' => 'Nutec Ceiling Boards', 'image' => 'images/products/nutec_ceiling.png'],
        ['name' => 'Plaster Boards', 'image' => 'images/products/plaster_ceiling.png'],
        ['name' => 'Plasterboard Moisture Resistent', 'image' => 'images/products/moisture_resistent.png'],
        ['name' => 'PVC Ceiling Boards', 'image' => 'images/products/pvc_ceiling.png'],
        ['name' => 'Pine Ceiling', 'image' => 'images/products/pine_ceiling.png'],
        ['name' => 'Ceiling Tiles Polysterene', 'image' => 'images/products/ceiling_tile.png'],
        ['name' => 'Trap Door Ceiling', 'image' => 'images/products/ceiling_trap.png'],
        ['name' => 'Shadowline Plaster Trim', 'image' => 'images/products/trim_ceiling.png'],
        ['name' => 'Corner Bead Galv', 'image' => 'images/products/corner_beads.png'],
        ['name' => 'Steel Brandering', 'image' => 'images/products/steel_brandering.png'],
      ],
      'Cornices' => [
        ['name' => 'Cornice Polystyrene', 'image' => 'images/products/cornice_poly.png'],
        ['name' => 'Cornice Leaf White', 'image' => 'images/products/cornice_leaf.png'],
        ['name' => 'Cornice 2m Crest', 'image' => 'images/products/cornice_crest.png'],
        ['name' => 'Dado Rail Polyurethane', 'image' => 'images/products/dado_rail.png'],
        ['name' => 'Cornice Polyurethane', 'image' => 'images/products/cornice_polyure.png'],
        ['name' => 'PVC Cornice', 'image' => 'images/products/cornice_pvc.png'],
        ['name' => 'Rhino Cove Cornice', 'image' => 'images/products/rhino_cornice.png'],
        ['name' => 'Pine Cornice', 'image' => 'images/products/pine_cornice.png'],
      ],
      'Tiles' => [
        ['name' => 'Tile MR44630T Stone Grey', 'image' => 'images/products/tile_grey.png'],
        ['name' => 'Tile PD Stone Brown Ceramic', 'image' => 'images/products/tile_brown.png'],
        ['name' => 'Tile Porcelain White MRP66003Z', 'image' => 'images/products/porcelin_white.png'],
        ['name' => 'Floor Tile Ivory', 'image' => 'images/products/ivory.png'],
        ['name' => 'Tile Wood Mix Ceramic Matt', 'image' => 'images/products/matt.png'],
        ['name' => 'Floor Tile Black', 'image' => 'images/products/black_tile.png'],
      ],
      'Tile Adhesive and Grout' => [
        ['name' => 'Weber Tile Grout', 'image' => 'images/products/grout.png'],
        ['name' => 'Weber Tylon Adhesive', 'image' => 'images/products/web_tylon.png'],
        ['name' => 'Tile Magic Tylon', 'image' => 'images/products/magic_tylon.png'],
        ['name' => 'Weber Porcelain Tylon', 'image' => 'images/products/porcelin_tylon.png'],
        ['name' => 'Tile Bond Liquid', 'image' => 'images/products/tile_bond.png'],
        ['name' => 'Jabulani Tylon 20kg', 'image' => 'images/products/jb_adhesive1.webp'],
      ],
      'Flooring' => [
        ['name' => 'Laminate Flooring Summer Biege', 'image' => 'images/products/summer_beige.png'],
        ['name' => 'Laminate Flooring OAK Brown', 'image' => 'images/products/oak_brown.png'],
        ['name' => 'Laminate Flooring Slate', 'image' => 'images/products/slate_flooring.png'],
        ['name' => 'Pine Flooring', 'image' => 'images/products/pine_flooring.png'],
        ['name' => 'Vinyl Flooring', 'image' => 'images/products/vinyl_flooring.png'],
      ],
      'Carpet and Accessories' => [
        ['name' => 'MultiFloor Carpet Vinyl OAK', 'image' => 'images/products/chaket_oak.png'],
        ['name' => 'MultiFloor Carpet Vinyl Brown', 'image' => 'images/products/brown_carpet.png'],
        ['name' => 'MultiFloor Rugs', 'image' => 'images/products/rugs.png'],
        ['name' => 'Tile Carpet', 'image' => 'images/products/tile_carpet.png'],
        ['name' => 'Joiner Board', 'image' => 'images/products/board_joiner.png'],
        ['name' => 'Carpet Edge Aluminium', 'image' => 'images/products/carpet_edge_aluminium.png'],
        ['name' => 'Trim Edge Corner Aluminium ', 'image' => 'images/products/trim_edge_aluminium_corner.png'],
      ],
      'Boards' => [
        ['name' => 'PG BISON ChipBoards', 'image' => 'images/products/chipboard.png'],
        ['name' => 'Pine Plywood Boards', 'image' => 'images/products/pine_plywood.png'],
        ['name' => 'PG BISON Melawood Boards', 'image' => 'images/products/melawood.png'],
        ['name' => 'PG BISON Supawood Boards', 'image' => 'images/products/supawood.png'],
        ['name' => 'Normal Hardboard Brown', 'image' => 'images/products/hardboard.png'],
        ['name' => 'Shutter Boards', 'image' => 'images/products/shutter_board.png'],
        ['name' => 'Orientel Standard Board ', 'image' => 'images/products/osb.png'],
        ['name' => 'Shelving Boards', 'image' => 'images/products/shelving_board.png'],
      ],
      'Decking and Cladding' => [
        ['name' => 'Composite Wall Cladding', 'image' => 'images/products/composite.png'],
        ['name' => 'Slatted Cladding', 'image' => 'images/products/slatted.png'],
        ['name' => 'Decking Normal', 'image' => 'images/products/decking.png'],
        ['name' => 'Decking Pine', 'image' => 'images/products/pine_decking.png'],
      ],
      'Mouldings and PAR Timber' => [
        ['name' => 'Pine Skirting', 'image' => 'images/products/skirting_pine.png'],
        ['name' => 'Pine Coverstrip', 'image' => 'images/products/coverstrip.png'],
        ['name' => 'Hardwood PAR', 'image' => 'images/products/hardwoodPar.png'],
        ['name' => 'Laminated Skirting', 'image' => 'images/products/laminate_skirting.png'],
        ['name' => 'PAR Timber', 'image' => 'images/products/par_timber.png'],
        ['name' => 'Mouldings', 'image' => 'images/products/raiel_moulding.png'],
      ],
      'Poles and Exotic Timber' => [
        ['name' => 'Treated Poles CCA All Size', 'image' => 'images/products/treated_pole.png'],
        ['name' => 'Untreated Poles All Size', 'image' => 'images/products/untreated_pole.png'],
        ['name' => 'Exotic Timber All Size', 'image' => 'images/products/timber.png'],
      ],
      'Edging' => [
        ['name' => 'Edging PVC Black', 'image' => 'images/products/edging_black.png'],
        ['name' => 'Edging PVC Gloss White', 'image' => 'images/products/edging_gloss_white.png'],
        ['name' => 'Edging PVC Vence', 'image' => 'images/products/edging_vence.png'],
        ['name' => 'Edging PVC PVC Summer Oak', 'image' => 'images/products/edging_summer_oak.png'],
        ['name' => 'Edging PVC Grey', 'image' => 'images/products/edging_grey.png'],
        ['name' => 'Edging PVC Blue', 'image' => 'images/products/edging_blue.png'],
      ],
      'Safety and Protective Wear' => [
        ['name' => 'Hard Hat All Colours', 'image' => 'images/products/hardhat_blue.png'],
        ['name' => 'Latex Gloves', 'image' => 'images/products/latex_gloves.png'],
        ['name' => 'Pioneer Reflective West', 'image' => 'images/products/pioneer_reflective_west.png'],
        ['name' => 'Everigard Safety Mask Respiratior', 'image' => 'images/products/mask_respirator.png'],
        ['name' => 'Everigard Faceshield Clear', 'image' => 'images/products/everigard_faceshield_clear.png'],
        ['name' => 'Rainsuit Reflective', 'image' => 'images/products/rainsuit_reflective.png'],
        ['name' => 'Safety Boot', 'image' => 'images/products/safety_boot.png'],
        ['name' => 'Pioneer Reflective Jacket', 'image' => 'images/products/pioneer_reflective_jacket.png'],
        ['name' => 'Everigard Classic Earmuff', 'image' => 'images/products/earmuff.png'],
      ],
      'Window and Door Accessories' => [
        ['name' => 'Door Handle Victorian Silver', 'image' => 'images/products/door_handle_victorian.png'],
        ['name' => 'Door Handle Matt Black', 'image' => 'images/products/door_handle_matt_black.png'],
        ['name' => 'Yale Lockset 2 Liver', 'image' => 'images/products/yale_lock_2l.png'],
        ['name' => '3 Liver Lockset', 'image' => 'images/products/3liver_lockset.png'],
        ['name' => 'Front Key cut', 'image' => 'images/products/key.png'],
        ['name' => 'Window Handle Black', 'image' => 'images/products/window_handle.png'],
        ['name' => 'Window Stay Set', 'image' => 'images/products/window_stay.png'],
        ['name' => 'Hinges', 'image' => 'images/products/Hinges.png'],
        ['name' => 'Hinge Butt Steel', 'image' => 'images/products/hinge_butt.png'],
        ['name' => 'Door Closer Grey', 'image' => 'images/products/door_closer.png'],
      ],
      'Chain, Clamps and Aluminium Profile' => [
        ['name' => 'Hose Clamp', 'image' => 'images/products/hose_clamp.png'],
        ['name' => 'Clamp Wire Rope', 'image' => 'images/products/clamp_wire_rope.png'],
        ['name' => 'Chain All Sizes', 'image' => 'images/products/chain.png'],
        ['name' => 'T Trim Aluminium', 'image' => 'images/products/t_trim_aluminium.png'],
        ['name' => 'Aluminium flat bar', 'image' => 'images/products/aluminium_flat_bar.png'],
        ['name' => 'Aluminium Angle Equal', 'image' => 'images/products/aluminium_angle_equal.png'],
      ],
      'Power and Building Tools' => [
        ['name' => 'Impact Drill 680W', 'image' => 'images/products/impact_drill_680w.png'],
        ['name' => 'Angle Grinder', 'image' => 'images/products/angle_grinder.png'],
        ['name' => 'Aspirator Air Blower', 'image' => 'images/products/aspirator_air_blower.png'],
        ['name' => 'Demolition Hammer', 'image' => 'images/products/demolition_hammer.png'],
        ['name' => 'Circular Saw 18V', 'image' => 'images/products/circular_saw_18v.png'],
        ['name' => 'Aluminium Ladder', 'image' => 'images/products/aluminium_ladder.png'],
        ['name' => 'Jig Saw 800W', 'image' => 'images/products/jig_saw_800w.png'],
        ['name' => 'Bruno hammer All Steel', 'image' => 'images/products/bruno_hammer_all_steel.png'],
        ['name' => 'Spanner Set', 'image' => 'images/products/spanner_set.png'],
        ['name' => 'Plaster Trowel', 'image' => 'images/products/plaster_trowel.png'],
      ],
      'Gardening Tools' => [
        ['name' => 'Electric Lawn Mower', 'image' => 'images/products/electric_lawn_mower.png'],
        ['name' => 'Grass Trimmer & Bush Cutter', 'image' => 'images/products/grass_trimmer.png'],
        ['name' => 'Garden Shoverl', 'image' => 'images/products/garden_shovel.png'],
        ['name' => 'Hedge Shear', 'image' => 'images/products/hedge_shear.png'],
        ['name' => 'Pruning Shear', 'image' => 'images/products/pruning_shear.png'],
        ['name' => 'Lopper', 'image' => 'images/products/Lopper.png'],
      ],
      'Waterproofing' => [
        ['name' => 'Waterproof Tape', 'image' => 'images/products/waterproof_tape.png'],
        ['name' => 'Duram Waterproofer Paint', 'image' => 'images/products/duram_waterproof.png'],
        ['name' => 'Waterproofing Membrane', 'image' => 'images/products/waterproofing_membrane.png'],
        ['name' => 'RainKote Paint 5L & 20L', 'image' => 'images/products/rain_kote.png'],
        ['name' => 'Cement Waterproofer 40', 'image' => 'images/products/cement_waterproofer_40.png'],
        ['name' => 'FlexiKote Paint 5L & 20L', 'image' => 'images/products/flexi_kote.png'],
      ],
      'Enamel and PVA' => [
        ['name' => 'Safari Gloss Enamel Paints', 'image' => 'images/products/safari_gloss_enamel.png'],
        ['name' => 'Medal Gloss Enamel Paints', 'image' => 'images/products/medal_high_gloss_enamel.png'],
        ['name' => 'Dulux Gloss Enamel Paints', 'image' => 'images/products/dulux_gloss_enamel.png'],
        ['name' => 'Duram Enamel Paints', 'image' => 'images/products/duram_enamel_trim.png'],
        ['name' => 'Excelsior All Purpose Enamel', 'image' => 'images/products/excelsior_allpurpose_gloss_enamel.png'],
        ['name' => 'Plascon Stoep Enamel Paints', 'image' => 'images/products/plascon_stoep_enamel.png'],
        ['name' => 'Dulux Arclyc Paints', 'image' => 'images/products/dulux_arclyic_pva.png'],
        ['name' => 'Supa PVA Paints', 'image' => 'images/products/supa_pva.png'],
        ['name' => 'Duram Armaguard Paints', 'image' => 'images/products/duram_armaguard.png'],
        ['name' => 'Super PVA Paints', 'image' => 'images/products/super_pva.png'],
        ['name' => 'Leswika Arclyc PVA Paints', 'image' => 'images/products/leswika_pva.png'],
        ['name' => 'Duram Armatex Paints', 'image' => 'images/products/duram_armatex.png'],
      ],
      'Roof Paint' => [
        ['name' => 'Duram RoofKote', 'image' => 'images/products/roof_kote.png'],
        ['name' => 'Leswika Roof Paint', 'image' => 'images/products/leswika_pva.png'],
        ['name' => 'Dulux RoofGuard', 'image' => 'images/products/dulux_roofgurad.png'],
        ['name' => 'Plascon Roof Paint', 'image' => 'images/products/plascon_roof.png'],
        ['name' => 'Duram Cool Tech Roof', 'image' => 'images/products/duram_cooltech.png'],
      ],
      'Wood Coating' => [
        ['name' => 'Dulux Woodgard', 'image' => 'images/products/dulux_woodgard.png'],
        ['name' => 'Plascon Woodcare', 'image' => 'images/products/plascon_woodcare.png'],
        ['name' => 'Wood Varnish', 'image' => 'images/products/wood_varnish.png'],
        ['name' => 'Floor Varnish', 'image' => 'images/products/floor_varnish.png'],
        ['name' => 'Duram Woodseal', 'image' => 'images/products/duram_woodseal.png'],
        ['name' => 'WoodFiller Bummer', 'image' => 'images/products/wood_filler_bummer.png'],
        ['name' => 'Alcolin Wood Filler', 'image' => 'images/products/woodfiller.png'],
      ],
      'Paint Accessories' => [
        ['name' => 'Paint Brush 100MM', 'image' => 'images/products/paint_brush_100mm.png'],
        ['name' => 'Paint Brush 150MM', 'image' => 'images/products/paint_brush_150mm.png'],
        ['name' => 'Paint Brush 50MM', 'image' => 'images/products/paint_brush_50mm.png'],
        ['name' => 'Paint Roller', 'image' => 'images/products/paint_roller.png'],
        ['name' => 'Paint Roller Handle', 'image' => 'images/products/paint_roller_handle.png'],
        ['name' => 'Paint Roller Extension Pole', 'image' => 'images/products/extension_pole.png'],
        ['name' => 'Paint Scraper', 'image' => 'images/products/paint_scraper.png'],
        ['name' => 'Paint Roller Tray Set', 'image' => 'images/products/paint_tray_set.png'],
        ['name' => 'Paint Liquids Mixer', 'image' => 'images/products/paint_mixer.png'],
      ],
      'Bathroomware' => [
        ['name' => 'Urinal Pacfic Back Entry', 'image' => 'images/products/urinal_pacific_back_entry.png'],
        ['name' => 'Basin Pedestal Black', 'image' => 'images/products/basin_pedestaLblack.png'],
        ['name' => 'Toilet Pan Astina White', 'image' => 'images/products/toilet_pan_astina_white.png'],
        ['name' => 'Toilet Pan Black Vip', 'image' => 'images/products/toilet_pan_black_gold.png'],
        ['name' => 'Basin Pedestal Full', 'image' => 'images/products/basin_full_pedestal.png'],
        ['name' => 'Shower Door Black Mosaic', 'image' => 'images/products/shower_door_black_mosaic.png'],
        ['name' => 'Shower Rose Thin Square', 'image' => 'images/products/shower_rose_thin_sq.png'],
        ['name' => 'Shower Room Luxury Vip', 'image' => 'images/products/shower_room_luxury_vip.png'],
        ['name' => 'Bath Oragami White', 'image' => 'images/products/bath_oragami_white.png'],
        ['name' => 'Semi Frame White Strip ShowerRoom', 'image' => 'images/products/semi_frame_white_strip_shower_door.png'],
        ['name' => 'Vanity Cabinet 2 Door With Besan', 'image' => 'images/products/vanity_cabinet_2door_with_besan.png'],
      ],
      'Kitchen' => [
        ['name' => 'Sink Mixer Tap High Rise', 'image' => 'images/products/sink_mixer_high_rise.png'],
        ['name' => 'Sink Tap DeckType Quartz', 'image' => 'images/products/sink_mixer_deck_type_quartz.png'],
        ['name' => 'Sink DropIn without Waste Cam', 'image' => 'images/products/sink_dropin_without_waste_cam.png'],
        ['name' => 'Sink With Waste Cam', 'image' => 'images/products/sink_waste_cam_africa.png'],
        ['name' => 'Kitchen Top Unit White', 'image' => 'images/products/kitchen_top_unit_white.png'],
        ['name' => 'Kitchen Base unit 4 Drawer', 'image' => 'images/products/kitchen_base_unit_4drawer.png'],
        ['name' => 'Kitchen over Sink Dish Rack', 'image' => 'images/products/kitchen_over_sink_dish_rack.png'],
        ['name' => 'Washthrough Sink Double', 'image' => 'images/products/wash_through_double.png'],
        ['name' => 'Sigle Sink Cabinet', 'image' => 'images/products/single_sink_cabinet.png'],
      ],
      'Pipes,Waste Traps and Fittings' => [
        ['name' => 'Reducing Coupler', 'image' => 'images/products/reducing_coupler.png'],
        ['name' => 'Comp PP Coupler Hdpe', 'image' => 'images/products/comp_pp_coupler_hdpe.png'],
        ['name' => 'Tee Galvanised', 'image' => 'images/products/tee_galvanised.png'],
        ['name' => 'Elbow 90 deg 22mm Copper', 'image' => 'images/products/elbow_90deg_22m_copper.png'],
        ['name' => 'MultiLayer Pipe 22m Coil', 'image' => 'images/products/multilayer_pipe_22m_coil.png'],
        ['name' => 'Trap P 32x40mm', 'image' => 'images/products/trap_p_32x40mm_mini.png'],
        ['name' => 'Bottle Trap with Outlet Pipe', 'image' => 'images/products/bottle_trap_tubulartype_with_outletPipe.png'],
        ['name' => 'Shower Trap Brass Square', 'image' => 'images/products/shower_trap_brass_square.png'],
        ['name' => 'Poly Cop Pipe 22mm & 15mm', 'image' => 'images/products/polycop_pipe_22mm_15mm.png'],
      ],
      'Geysers and RainWater Goods' => [
        ['name' => 'SuperLine Geyser 50 to 200L', 'image' => 'images/products/superline_geyser_50_200L.png'],
        ['name' => 'Solar Geyser Direct 100L', 'image' => 'images/products/geyser_direct_solar.png'],
        ['name' => 'Solar Geyser 150L Inst Kit Inc', 'image' => 'images/products/solar_geyser_roof_installation_kit_included.png'],
        ['name' => 'Control Isolator & Relief Valve', 'image' => 'images/products/control_isolator_relief_valve.png'],
        ['name' => 'Pressure Control Valve', 'image' => 'images/products/pressure_control_valve.png'],
        ['name' => 'Gutter Galvanized Square', 'image' => 'images/products/gutter_galv_square.png'],
        ['name' => 'Downpipe Square', 'image' => 'images/products/downpipe_sqaure.png'],
        ['name' => 'Gutter Bracket', 'image' => 'images/products/gutter_bracket.png'],
        ['name' => 'Gutter Downpipe Offset Bend', 'image' => 'images/products/gutter_downpipe_offset_bend.png'],
        ['name' => 'Gutter PVC Streamline Fasc Bracket', 'image' => 'images/products/gutter_pvc_streamline_fascia_bracket.png'],
      ],
      'Plumbing Accessories' => [
        ['name' => 'Gate Valve Brass', 'image' => 'images/products/gate_valve_brass.png'],
        ['name' => 'Ball valve Lever', 'image' => 'images/products/ball_valve_lever.png'],
        ['name' => 'Plunger Drain', 'image' => 'images/products/plunger_drain.png'],
        ['name' => 'Basin Chain With Stay', 'image' => 'images/products/basin_chain_with_stay.png'],
        ['name' => 'Trigger Spray Set Round', 'image' => 'images/products/trigger_spray_set_round.png'],
        ['name' => 'Adjustable Wrench', 'image' => 'images/products/adjustable_wrench.png'],
        ['name' => 'PVC Weld Cement', 'image' => 'images/products/pvc_weld_cement.png'],
        ['name' => 'Blow Torch Normal', 'image' => 'images/products/blow_torch.png'],
        ['name' => 'Basin Plug', 'image' => 'images/products/sink_plug.png'],
      ],
      'Wiring and Cables' => [
        ['name' => 'House Wire 6mm Blue', 'image' => 'images/products/house_wire_6mm_blue.png'],
        ['name' => 'Electrical Cable Flat Twin Earth', 'image' => 'images/products/electrical_cable_flat_twin_earth.png'],
        ['name' => 'Trunking PVC', 'image' => 'images/products/trunking_pvc.png'],
        ['name' => 'House Wire 6mm Red', 'image' => 'images/products/house_wire_6mm_red.png'],
        ['name' => 'Welding Cables', 'image' => 'images/products/welding_cables.png'],
        ['name' => 'House Wire 16mm Black', 'image' => 'images/products/house_wire_16mm_black.png'],
        ['name' => 'General Purpose Wire', 'image' => 'images/products/general_purpose_wire.png'],
        ['name' => 'Cable Armoured Wire 2Core', 'image' => 'images/products/cable_armoured_steel_wire_2core.png'],
        ['name' => '3 Core R1 Cable Wire', 'image' => 'images/products/3core_r1_cable_wire.png'],
        ['name' => 'Earth Wire Bare', 'image' => 'images/products/earth_wire_bare.png'],
      ],
      'Plugs, Sockets and Bulbs' => [
        ['name' => 'Socket Single White', 'image' => 'images/products/socket_single_white.png'],
        ['name' => 'Switch 1Lever 1way Charcoal', 'image' => 'images/products/switch_1lever_1way+charcoal.png'],
        ['name' => '2 Lever Switch', 'image' => 'images/products/2_lever_switch.png'],
        ['name' => '4 Lever Switch', 'image' => 'images/products/4_lever_switch_1way.png'],
        ['name' => 'Switch SSO Combo + 2USB Sock', 'image' => 'images/products/switch_sso_combo_2usb.png'],
        ['name' => 'Globe LED Rechargable', 'image' => 'images/products/globe_led_rechargable.png'],
        ['name' => 'LED Strip Light', 'image' => 'images/products/led_strip_light.png'],
        ['name' => 'Lamp Infrared', 'image' => 'images/products/lamp_infrared.png'],
        ['name' => 'Globe LED Filament', 'image' => 'images/products/globe_led_filament.png'],
        ['name' => 'Lantern Light 6 Panel', 'image' => 'images/products/lantern_6panel.png'],
      ],
      'Electrical Accessories' => [
        ['name' => 'Socket Single White', 'image' => 'images/products/socket_single_white.png'],
        ['name' => 'Switch 1Lever 1way Charcoal', 'image' => 'images/products/switch_1lever_1way+charcoal.png'],
      ]
    ];

    \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0;');
    Product::truncate();
    \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    $allCategories = Category::all();

    foreach ($productsBySubcategory as $subCatName => $products) {
      // Find the subcategory using slug matching or name directly
      $subCategory = $allCategories->first(function ($cat) use ($subCatName) {
        // Must have a parent_id to be a subcategory, and name must match
        return $cat->parent_id !== null && strtolower(trim($cat->name)) === strtolower(trim($subCatName));
      });

      if ($subCategory) {
        foreach ($products as $prodData) {
          Product::create([
            'name' => $prodData['name'],
            'slug' => Str::slug($prodData['name']) . '-' . strtolower(Str::random(4)),
            'sku' => strtoupper(Str::random(8)),
            'description' => '<p>High quality ' . $prodData['name'] . ' ready for bulk purchase.</p>',
            'price' => rand(100, 5000) / 10,
            'is_featured' => (rand(1, 100) > 85),
            'category_id' => $subCategory->parent_id,
            'subcategory_id' => $subCategory->id,
            'image' => $prodData['image'],
          ]);
        }
      } else {
        \Log::warning("Product seeder could not find subcategory: {$subCatName}");
      }
    }
  }
}
