<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
  0 => 
  [
    'name' => 'Bricks & Blocks',
    'slug' => 'bricks-blocks-1',
    'description' => 'Jabulani Bricks & Blocks - High quality construction material.',
    'category_id' => 1,
    'brand_id' => NULL,
    'sku' => 'JB-822OIANO',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/jabulani_blocks.webp',
  ],
  1 => 
  [
    'name' => 'Aluminium Windows & Doors',
    'slug' => 'aluminium-windows-doors-3',
    'description' => 'Jabulani Aluminium Windows & Doors - High quality construction material.',
    'category_id' => 1,
    'brand_id' => NULL,
    'sku' => 'JB-4GWP9JZA',
    'price' => '5.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Aluminium_Door.webp',
  ],
  2 => 
  [
    'name' => 'Structural & Concrete Elements',
    'slug' => 'structural-concrete-elements-4',
    'description' => 'Jabulani Structural & Concrete Elements - High quality construction material.',
    'category_id' => 1,
    'brand_id' => NULL,
    'sku' => 'JB-MHPBNUJM',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Lintel_piller.webp',
  ],
  3 => 
  [
    'name' => 'Roofing',
    'slug' => 'roofing-5',
    'description' => 'Jabulani Roofing - High quality construction material.',
    'category_id' => 1,
    'brand_id' => NULL,
    'sku' => 'JB-OUVOCUYZ',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/ROOF_FLOOR2.webp',
  ],
  4 => 
  [
    'name' => 'Jabulani Tile Adhesive',
    'slug' => 'jabulani-tile-adhesive-6',
    'description' => 'Jabulani Jabulani Tile Adhesive - High quality construction material.',
    'category_id' => 1,
    'brand_id' => NULL,
    'sku' => 'JB-WHXUPSDN',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/jb_adhesive.webp',
  ],
  5 => 
  [
    'name' => 'Jabulani Crush Stone',
    'slug' => 'jabulani-crush-stone-7',
    'description' => 'Jabulani Jabulani Crush Stone - High quality construction material.',
    'category_id' => 1,
    'brand_id' => NULL,
    'sku' => 'JB-I4TBN0W1',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/crush2.webp',
  ],
  6 => 
  [
    'name' => 'Structural & Concrete Products',
    'slug' => 'structural-concrete-products-9',
    'description' => 'Jabulani Structural & Concrete Products - High quality construction material.',
    'category_id' => 3,
    'brand_id' => NULL,
    'sku' => 'JB-YXX95626',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Lintel_piller.webp',
  ],
  7 => 
  [
    'name' => 'Cements & Premixes',
    'slug' => 'cements-premixes-10',
    'description' => 'Jabulani Cements & Premixes - High quality construction material.',
    'category_id' => 3,
    'brand_id' => NULL,
    'sku' => 'JB-46OV1PGK',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Cement.webp',
  ],
  8 => 
  [
    'name' => 'Structural Steel',
    'slug' => 'structural-steel-11',
    'description' => 'Jabulani Structural Steel - High quality construction material.',
    'category_id' => 3,
    'brand_id' => NULL,
    'sku' => 'JB-DX3OPO7Y',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/steel.webp',
  ],
  9 => 
  [
    'name' => 'Reinforcing & Underlay',
    'slug' => 'reinforcing-underlay-12',
    'description' => 'Jabulani Reinforcing & Underlay - High quality construction material.',
    'category_id' => 3,
    'brand_id' => NULL,
    'sku' => 'JB-ZT5VFXVP',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Fence.webp',
  ],
  10 => 
  [
    'name' => 'Roof Tiles',
    'slug' => 'roof-tiles-13',
    'description' => 'Jabulani Roof Tiles - High quality construction material.',
    'category_id' => 4,
    'brand_id' => NULL,
    'sku' => 'JB-O41Q3LN8',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/ROOF_FLOOR.webp',
  ],
  11 => 
  [
    'name' => 'Roof Sheeting',
    'slug' => 'roof-sheeting-14',
    'description' => 'Jabulani Roof Sheeting - High quality construction material.',
    'category_id' => 4,
    'brand_id' => NULL,
    'sku' => 'JB-W4YZOFOY',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Sheeting.webp',
  ],
  12 => 
  [
    'name' => 'Fascia & Barge',
    'slug' => 'fascia-barge-15',
    'description' => 'Jabulani Fascia & Barge - High quality construction material.',
    'category_id' => 4,
    'brand_id' => NULL,
    'sku' => 'JB-1NBXYTHH',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/fascia.webp',
  ],
  13 => 
  [
    'name' => 'Ceiling Boards,Tiles & Pine',
    'slug' => 'ceiling-boardstiles-pine-16',
    'description' => 'Jabulani Ceiling Boards,Tiles & Pine - High quality construction material.',
    'category_id' => 4,
    'brand_id' => NULL,
    'sku' => 'JB-DQDRARLY',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/ceiling.webp',
  ],
  14 => 
  [
    'name' => 'Cornices',
    'slug' => 'cornices-17',
    'description' => 'Jabulani Cornices - High quality construction material.',
    'category_id' => 4,
    'brand_id' => NULL,
    'sku' => 'JB-KXMTF6K6',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Cornice.webp',
  ],
  15 => 
  [
    'name' => 'Tiles',
    'slug' => 'tiles-18',
    'description' => 'Jabulani Tiles - High quality construction material.',
    'category_id' => 5,
    'brand_id' => NULL,
    'sku' => 'JB-8XOKNPC2',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Tiles2.webp',
  ],
  16 => 
  [
    'name' => 'Tile Adhesives & Grouts',
    'slug' => 'tile-adhesives-grouts-19',
    'description' => 'Jabulani Tile Adhesives & Grouts - High quality construction material.',
    'category_id' => 5,
    'brand_id' => NULL,
    'sku' => 'JB-YA5REGX5',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/adhesive.webp',
  ],
  17 => 
  [
    'name' => 'Flooring',
    'slug' => 'flooring-20',
    'description' => 'Jabulani Flooring - High quality construction material.',
    'category_id' => 5,
    'brand_id' => NULL,
    'sku' => 'JB-6VY2RPMA',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Flooring.webp',
  ],
  18 => 
  [
    'name' => 'Carpet & Accessories',
    'slug' => 'carpet-accessories-21',
    'description' => 'Jabulani Carpet & Accessories - High quality construction material.',
    'category_id' => 5,
    'brand_id' => NULL,
    'sku' => 'JB-XTV5FZOZ',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Carpet.webp',
  ],
  19 => 
  [
    'name' => 'Boards',
    'slug' => 'boards-22',
    'description' => 'Jabulani Boards - High quality construction material.',
    'category_id' => 6,
    'brand_id' => NULL,
    'sku' => 'JB-IWT3M4BV',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Plywood.webp',
  ],
  20 => 
  [
    'name' => 'Decking & Cladding',
    'slug' => 'decking-cladding-23',
    'description' => 'Jabulani Decking & Cladding - High quality construction material.',
    'category_id' => 6,
    'brand_id' => NULL,
    'sku' => 'JB-TP8RCSOH',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Cladding.webp',
  ],
  21 => 
  [
    'name' => 'Mouldings & PAR Timber',
    'slug' => 'mouldings-par-timber-24',
    'description' => 'Jabulani Mouldings & PAR Timber - High quality construction material.',
    'category_id' => 6,
    'brand_id' => NULL,
    'sku' => 'JB-MB7STA3P',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Mouldings.webp',
  ],
  22 => 
  [
    'name' => 'Poles & Exotic Timber',
    'slug' => 'poles-exotic-timber-25',
    'description' => 'Jabulani Poles & Exotic Timber - High quality construction material.',
    'category_id' => 6,
    'brand_id' => NULL,
    'sku' => 'JB-N2XJNAUU',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Poles.webp',
  ],
  23 => 
  [
    'name' => 'Edging',
    'slug' => 'edging-26',
    'description' => 'Jabulani Edging - High quality construction material.',
    'category_id' => 6,
    'brand_id' => NULL,
    'sku' => 'JB-ACALMFVW',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Edging.webp',
  ],
  24 => 
  [
    'name' => 'Safety & Protective Wear',
    'slug' => 'safety-protective-wear-27',
    'description' => 'Jabulani Safety & Protective Wear - High quality construction material.',
    'category_id' => 7,
    'brand_id' => NULL,
    'sku' => 'JB-XSZFSZCU',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/safety.webp',
  ],
  25 => 
  [
    'name' => 'Window & Door Accessories',
    'slug' => 'window-door-accessories-28',
    'description' => 'Jabulani Window & Door Accessories - High quality construction material.',
    'category_id' => 7,
    'brand_id' => NULL,
    'sku' => 'JB-EHJLOC99',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/LOCKS.webp',
  ],
  26 => 
  [
    'name' => 'Chain, Clamps & Aluminium Profile',
    'slug' => 'chain-clamps-aluminium-profile-29',
    'description' => 'Jabulani Chain, Clamps & Aluminium Profile - High quality construction material.',
    'category_id' => 7,
    'brand_id' => NULL,
    'sku' => 'JB-KCHSJYZE',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Alu_profile.webp',
  ],
  27 => 
  [
    'name' => 'Power & Building Tools',
    'slug' => 'power-building-tools-30',
    'description' => 'Jabulani Power & Building Tools - High quality construction material.',
    'category_id' => 7,
    'brand_id' => NULL,
    'sku' => 'JB-NA0OFSGK',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Power_tools.webp',
  ],
  28 => 
  [
    'name' => 'Gardening Tools',
    'slug' => 'gardening-tools-31',
    'description' => 'Jabulani Gardening Tools - High quality construction material.',
    'category_id' => 7,
    'brand_id' => NULL,
    'sku' => 'JB-TAL3OSML',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/garden.webp',
  ],
  29 => 
  [
    'name' => 'Waterproofing',
    'slug' => 'waterproofing-32',
    'description' => 'Jabulani Waterproofing - High quality construction material.',
    'category_id' => 8,
    'brand_id' => NULL,
    'sku' => 'JB-LZVMAA6V',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Waterproofing.webp',
  ],
  30 => 
  [
    'name' => 'Enamel & PVA',
    'slug' => 'enamel-pva-33',
    'description' => 'Jabulani Enamel & PVA - High quality construction material.',
    'category_id' => 8,
    'brand_id' => NULL,
    'sku' => 'JB-FHUKZJYK',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/PVA.webp',
  ],
  31 => 
  [
    'name' => 'Roof paint',
    'slug' => 'roof-paint-34',
    'description' => 'Jabulani Roof paint - High quality construction material.',
    'category_id' => 8,
    'brand_id' => NULL,
    'sku' => 'JB-P0KR7LNQ',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/RoofPaint.webp',
  ],
  32 => 
  [
    'name' => 'Wood Coating',
    'slug' => 'wood-coating-35',
    'description' => 'Jabulani Wood Coating - High quality construction material.',
    'category_id' => 8,
    'brand_id' => NULL,
    'sku' => 'JB-C4SE9QIW',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/WoodCoat.webp',
  ],
  33 => 
  [
    'name' => 'Paint Accessories',
    'slug' => 'paint-accessories-36',
    'description' => 'Jabulani Paint Accessories - High quality construction material.',
    'category_id' => 8,
    'brand_id' => NULL,
    'sku' => 'JB-QTFISZXH',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/PaintBrush.webp',
  ],
  34 => 
  [
    'name' => 'Bathtroomware',
    'slug' => 'bathtroomware-37',
    'description' => 'Jabulani Bathtroomware - High quality construction material.',
    'category_id' => 9,
    'brand_id' => NULL,
    'sku' => 'JB-TXJAT0F1',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Shower.webp',
  ],
  35 => 
  [
    'name' => 'Kitchen',
    'slug' => 'kitchen-38',
    'description' => 'Jabulani Kitchen - High quality construction material.',
    'category_id' => 9,
    'brand_id' => NULL,
    'sku' => 'JB-DWXDNP41',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/sink.webp',
  ],
  36 => 
  [
    'name' => 'Pipes, Waste Traps & Fittings',
    'slug' => 'pipes-waste-traps-fittings-39',
    'description' => 'Jabulani Pipes, Waste Traps & Fittings - High quality construction material.',
    'category_id' => 10,
    'brand_id' => NULL,
    'sku' => 'JB-AYGIZ9PC',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Pipes.webp',
  ],
  37 => 
  [
    'name' => 'Geysers & Rainwater Goods',
    'slug' => 'geysers-rainwater-goods-40',
    'description' => 'Jabulani Geysers & Rainwater Goods - High quality construction material.',
    'category_id' => 10,
    'brand_id' => NULL,
    'sku' => 'JB-ISZKCXE1',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/geyser.webp',
  ],
  38 => 
  [
    'name' => 'Plumbing Accessories',
    'slug' => 'plumbing-accessories-41',
    'description' => 'Jabulani Plumbing Accessories - High quality construction material.',
    'category_id' => 11,
    'brand_id' => NULL,
    'sku' => 'JB-PWMYDMRC',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/plumbingTools.webp',
  ],
  39 => 
  [
    'name' => 'Wiring & Cables',
    'slug' => 'wiring-cables-42',
    'description' => 'Jabulani Wiring & Cables - High quality construction material.',
    'category_id' => 11,
    'brand_id' => NULL,
    'sku' => 'JB-CE0UFCBU',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/cables.webp',
  ],
  40 => 
  [
    'name' => 'plugs, Sockets & Bulbs',
    'slug' => 'plugs-sockets-bulbs-43',
    'description' => 'Jabulani plugs, Sockets & Bulbs - High quality construction material.',
    'category_id' => 11,
    'brand_id' => NULL,
    'sku' => 'JB-PECNLJ6E',
    'price' => '0.00',
    'vat_rate' => '15.00',
    'is_featured' => 0,
    'status' => 'active',
    'image' => 'images/Bulbs.webp',
  ],
];

        foreach ($data as $item) {
            $matchKey = ['name' => $item['name'] ?? ''];
            if (isset($item['slug'])) $matchKey = ['slug' => $item['slug']];
            elseif (isset($item['title'])) $matchKey = ['title' => $item['title']];
            
            Product::updateOrCreate($matchKey, $item);
        }
    }
}
